version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/frontend"
    schedule:
      interval: "yearly"
    allow:
      - dependency-type: "direct"
      labels:
        - "dependencies"
        - "frontend"
